sudo: required
group: deprecated-2017Q3
services:
- docker
language: node_js
node_js:
- 9.11.1
env:
  global:
  - CC_TEST_REPORTER_ID=f9a7cc51d41f847d9b5c91f469606222755355ec9ea001c6bd7a16d20f45941f
  matrix:
    secure: 0hJrNGq2AHcxLBe8OYZaXasmZA6Ciqyzvhmx/+M9dnvyeRkNnLElFLYjaKbPfRjLo7KX8tuwJTMroPPcZ3Tygfn+aVMCgMkz5i6s7diJ/ybgkmZqZ4xiQqmRPqVYWSSdfzuMXI/vUSnNiY2cxIusJbNRDGUTVnirGt03+4ZwzrZ3YqMsZaYE3kj3Tnw38dg0Hbcq1QvCGPkxOY3ruwUcbuE86MpNotgiDGSTT2oGq3R681Q9z02Zm16jY1Uhs7fMBq5wJqGyFlm/MlCfWiLmEY/1PGXIA7kzUQQ/Q8A2eEtyAcv7mlCH7xFi2Z+2ZNuoz/WTgTBmg1BasjVmvUVscDjBfoj/1QzUUs1PUcrSmAd4f/5wk18o7xvowm1JqJkkeRU6bk9Y00J2WNoPRZ1j+rIgtXdJ6QKKQBd03oWjoWadFeg4N4loBVgrnHLm/j/DVaQc2Ux1Z3hmC34EI/zkoKcVagf8ASlTJrq6wptkExU9KjuFEsiYxlTavgFQnfXnjAzQbA1gaHHVB4n7wSel6oujipesoXscgoRx999NCngoc0SLcnHXlz74XIkhonDXkgsjM+gqaHUQDb4sQmXt3JSgTEJhersgaXkCNi7PLZUtjQidP0D/5OI0g4QQvajxSsSmYslLKNwLwzVDvXoxthmHRI3lwL36suIunrn1i1c=
before_script:
- npm install coveralls
- docker-compose -f docker-compose.test.yml up -d
script:
- docker exec -it tropical-hazards-front npm test
after_script:
- "./node_modules/coveralls/bin/coveralls.js < ./test/unit/coverage/lcov.info"
- docker-compose down --remove-orphans
after_success:
- docker login --username=_ --passwword=$(HEROKU_AUTHTAG) registry.heroku.com
- docker build -f Dockerfile.prod -t deploy_image
- |
  if[ "${TRAVIS_BRANCH}" == "development"]; them 
    echo "Deploying to homolog environment..."
    docker tag deploy_image registry.heroku.com/tropical-hazards-homolog/web
    docker push registry.heroku.com/tropical-hazards-homolog/web
  else if[ "${TRAVIS_BRANCH}" == "master"]; them 
    echo "Deploying to production environment..."
    docker tag deploy_image registry.heroku.com/tropical-hazards/web
    docker push registry.heroku.com/tropical-hazards/web
  else
    echo "Skipping deploy...";
  fi;
  fi;
    
