sudo: required

services:
- docker
language: node_js
node_js:
- 9.11.1
env:
  global:
  - CC_TEST_REPORTER_ID=f9a7cc51d41f847d9b5c91f469606222755355ec9ea001c6bd7a16d20f45941f
before_script:
- npm install coveralls
- docker-compose -f docker-compose.test.yml up -d
script:
- docker exec -it tropical-hazards-front npm test
after_script:
- "./node_modules/coveralls/bin/coveralls.js < ./test/unit/coverage/lcov.info"
- docker-compose down --remove-orphans
after_success:
- |
  if [ "${TRAVIS_BRANCH}" == "development" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    echo "Deploying to homolog environment..."
    docker build -f Dockerfile -t $DOCKERHUB_ORG/tropical-hazards-front:latest .
    docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASSWORD
    docker push $DOCKERHUB_ORG/tropical-hazards-front:latest
    docker run cdrx/rancher-gitlab-deploy upgrade --rancher-url $RANCHER_URL --rancher-key $RANCHER_ACCESS_KEY --rancher-secret $RANCHER_SECRET_KEY --environment Default --stack Observ --service frontend --finish-upgrade
    else
      echo "Skipping deploy...";
  fi;
