sudo: required
group: deprecated-2017Q3
services:
- docker
language: node_js
node_js:
- 9.11.1
env:
  global:
  - secure: fjUg+ke1dH2GFqHNX4rez5OGISQMe+b81xyz0SmRqwGPwDklZX4nnJDbgZne34f9HTDTDSJ7aocrhz2pdYH7/mRaZNdwm+qsGjf1InJDIlIHlKJafJCLzIkqeQRr1JxAft4gBpJiLOMAGSiBCrYo8M1Efxd81m4PUSk8vsvKqglnGAZkQvz/HX6xIaTLJiOYmPhLNRut7HibN457dwkXUNnSn+6+nzmk+dIrzqb7/687rueMMgjiGEt8Id3kLRjIcZOkwBGcjOUDdqJDabNq8F5f2uOkx3z9QuHe+WzQ8J0/qY0On195OzbdjapJcM0tIDJvtQFn1Vvt34NfaBG5kaZKjVAVTwivVMxhoTWBOwBax3tAsj+M9Gy0VswIyLOr82L0aGKV9pcApBnXDeO0xosudMfKpzHoMc4wKhuJNIaT0CVpGz5YAOKf9cOiomDj1WaYb2ERd3Fhv+WtuNwAeEp1XtXNevG4ZkFnQEv7mLtE2QzhBiyOKDjy3Y28OUhp4bAgwkBR+AZcQaLqMjdJJBDB9tpkr8XuNkYXyHEeqcIsR5yGOBLawIvSss11t0uCwOtCahmcFIDLrse9LmhnQ6zcP2cYK4f86c9QHFyianyyTyFy7s0zRVxcm/bx86MeEarfcV6zV1ILcGtzhnefX3K1lcQS9D1D0ta/oMYUZDQ=

  - CC_TEST_REPORTER_ID=f9a7cc51d41f847d9b5c91f469606222755355ec9ea001c6bd7a16d20f45941f
before_script:
- npm install coveralls
- docker-compose -f docker-compose.test.yml up -d
script:
- docker exec -it tropical-hazards-front npm test
after_script:
- "./node_modules/coveralls/bin/coveralls.js < ./test/unit/coverage/lcov.info"
- docker-compose down --remove-orphans
after_success:
- echo "$(HEROKU_TOKEN)"
- docker login --username=_ --password="$(HEROKU_TOKEN)" registry.heroku.com
- docker build -f Dockerfile.prod -t deploy_image .
- |
  if[ "${TRAVIS_BRANCH}" == "development"]; then 
    echo "Deploying to homolog environment..."  
    docker tag deploy_image registry.heroku.com/tropical-hazards-homolog/web
    docker push registry.heroku.com/tropical-hazards-homolog/web
  else if[ "${TRAVIS_BRANCH}" == "master"]; then
    echo "Deploying to production environment..."
    docker tag deploy_image registry.heroku.com/tropical-hazards/web
    docker push registry.heroku.com/tropical-hazards/web
  else
    echo "Skipping deploy...";
  fi;
  fi;
