version: '2'

services:
  th_bi-front:
    container_name: tropical-hazards-front
    build: .
    command: /bin/bash start.sh 
    volumes:
      - .:/TropicalHazards-BI-FrontEnd
    external_links:
      - 20181tropicalhazardsbi_default
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    networks:
      - default
      - 20181tropicalhazardsbi_default

networks:
  20181tropicalhazardsbi_default:
    external: true
